### ISSUE TITLE
It can't assume stream for some models.

### ISSUE THREAD

**Issue by liyiecho** [maki-chan/CaptureBateC#1]
![cff22523-6792-4831-a972-573610e6f37e](https://user-images.githubusercontent.com/5213722/27783729-fd282238-6009-11e7-9f24-a302ac4f218f.png)

If the HD icon appears on the page, it can't assume the stream.

**Comment by liyiecho** [comment]
If the HD icon appears on the page，it is  `_trns_h264/playlist.m3u8` not `_aac/playlist.m3u8`. So I solve the issuse by changed the code `"http.*_aac/playlist\\.m3u8"` to `"http.*/playlist\\.m3u8"` on [https://github.com/maki-chan/CaptureBateC/blob/master/main.c#L252](url)

**Comment by maki-chan** [comment]
I will have to fix this issue in the codebase then. Thank you for reporting this
